# Generated by Django 4.1.7 on 2023-04-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=255)),
                ('sit_places', models.PositiveSmallIntegerField()),
                ('is_broken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voyage_number', models.CharField(max_length=255)),
                ('time_departure', models.DateTimeField()),
                ('end_time_departure', models.DateTimeField()),
                ('days', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('third_name', models.CharField(max_length=255)),
                ('illness', models.BooleanField(default=False)),
                ('hours_worked', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_departure', models.DateField()),
                ('availableTickets', models.PositiveSmallIntegerField()),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='station.bus')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='station.driver')),
                ('voyage_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='station.defaultvoyage')),
            ],
        ),
    ]
