# Generated by Django 4.1.7 on 2023-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='availableTickets',
            new_name='available_tickets',
        ),
        migrations.AlterField(
            model_name='defaultvoyage',
            name='end_time_departure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='defaultvoyage',
            name='time_departure',
            field=models.TimeField(),
        ),
    ]
