# Generated by Django 4.1.7 on 2023-04-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_rename_availabletickets_voyage_available_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultvoyage',
            name='destination',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
