# Generated by Django 4.1.7 on 2023-04-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_defaultvoyage_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='bus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='station.bus'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='driver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='station.driver'),
        ),
    ]
